import { Login } from '@components/organisms'
import { Container } from '@mui/material'
import { styled } from '@mui/system'
import type { NextPage } from 'next'
import { useRouter } from 'next/navigation'
import { useSelector } from 'react-redux'
import Head from 'next/head'
import { useEffect } from 'react'
import { RootState } from 'redux/store'

const StyledContainer = styled(Container)(({ theme }) => {
  return {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '80vh',
  }
})

const Home: NextPage = () => {
  const auth = useSelector((state: RootState) => state.auth)
  const { isAuthenticated } = auth

  const router = useRouter()

  useEffect(() => {
    if (isAuthenticated) {
      router.push('/dashboard')
    }
  }, [isAuthenticated])

  return (
    <div>
      <Head>
        <title>Smart GK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledContainer>{!isAuthenticated && <Login />}</StyledContainer>
    </div>
  )
}

export default Home
